CREATE TABLE ACCOUNTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pwd VARCHAR(100) NOT NULL,
    pnum VARCHAR(15),
    username VARCHAR(50) NOT NULL,
    accesslvl ENUM('guest', 'user', 'verified user', 'admin') NOT NULL 
);

CREATE TABLE IMAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    imgname VARCHAR(100) NOT NULL
);


CREATE TABLE POSTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    descr TEXT NOT NULL,
    genre VARCHAR(50) NOT NULL,
    authorID INT NOT NULL,
    numUp INT DEFAULT 0,
    numDown INT DEFAULT 0,
    picID INT  NULL,
    FOREIGN KEY (authorID) REFERENCES ACCOUNTS(id),
    FOREIGN KEY (picID) REFERENCES IMAGES(id)
);